BlazorWasm support
IronLanguages/dlr pull request #256
Opened 2022-02-22 15:23 UTC by TwoUnderscorez

When trying to use IronPython3 from a Blazor web-assembly application, `Microsoft.Scripting.Runtime.SharedIO` throws an exception when trying to setup `stdin`, which is understandable, because there is none.

All I did is catch the exception and set the stream to `Stream.Null`.

2022-02-22 16:54 UTC, slozier requested changes
Thanks for the PR. My main concern with this approach is that if someone changes the order of the assignments (I think) it'll throw a PNSE instead of a `TypeInitializationException`. Probably better to fix `ConsoleInputStream` to not throw on initialization and then catch the PNSE.

I guess my other problem is I don't have a Blazor test rig to validate this. Any pointers on setting one up?

Related issue: https://github.com/IronLanguages/ironpython2/issues/769
Workaround: https://github.com/IronLanguages/ironpython2/issues/769#issuecomment-767590643

2022-02-24 09:58 UTC, TwoUnderscorez commented
@slozier Is that better?

2022-02-24 19:27 UTC, slozier approved these changes
Thanks, that works.

Going from a field to a property is a breaking change but I assume no one outside the assembly is using this... Also I think we lose thread safety on the singleton creation. Will need to look into it a bit more, but I guess I can fix it after the merge if required.

2022-02-26 12:41 UTC, TwoUnderscorez commented
@slozier Sorry, I don't quite understand how this is a breaking change. If you would point me in the right direction I might be able to make it a non-breaking change.

2022-02-26 13:45 UTC, slozier commented
@TwoUnderscorez I meant having `ConsoleInputStream.Instance` go from a field to a property is technically a binary breaking change (for example if assembly A uses a field from assembly B and you replace B with B' which contains a property instead, then A is broken). I don't think I'm really worried about breaking anyone with this particular scenario since the only consumer is in the same assembly - but it is a public type so it's not impossible...

An alternative approach would be to leave `ConsoleInputStream.Instance` as a field and change the constructor to not throw:
```C#
private ConsoleInputStream() {
    try {
        _input = Console.OpenStandardInput();
    } catch (PlatformNotSupportedException) {
        _input = Stream.Null;
    }
}
```

2022-03-10 19:33 UTC, TwoUnderscorez commented
@slozier I could do that, but I would have to leave the catch block in `ShareIO.InitializeInput` because 
```csharp
_inputEncoding = Console.InputEncoding;
_inputReader = Console.In;
``` 
also throw `PlatformNotSupportedException` (maybe only one of them), which I personally think is kind of ugly. Would you like me to do what you've suggested or merge as is currently?

2022-03-10 21:44 UTC, slozier commented
@TwoUnderscorez I think the PNSE try/catch you have in `InitializeInput` is fine, but I'd change the `ConsoleInputStream` to what I suggested instead.

2022-04-05 00:28 UTC, merged

2022-04-05 00:28 UTC, slozier commented
Thanks for the PR!